<?php
	/* path file controller */
	define("_PHISICAL_PATH_ADMIN_CONTROLLER",_PHISICAL_PATH_ADMIN.'controller/');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_WEBMASTER",_PHISICAL_PATH_ADMIN_CONTROLLER.'webmaster_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_LOGIN",_PHISICAL_PATH_ADMIN_CONTROLLER.'login_controller.php');

	define("_PHISICAL_PATH_ADMIN_CONTROLLER_SEO",_PHISICAL_PATH_ADMIN_CONTROLLER.'seo_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_CATEGORY",_PHISICAL_PATH_ADMIN_CONTROLLER.'category_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_CONTENT",_PHISICAL_PATH_ADMIN_CONTROLLER.'content_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_MEMBER",_PHISICAL_PATH_ADMIN_CONTROLLER.'member_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_COMPANY",_PHISICAL_PATH_ADMIN_CONTROLLER.'company_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_BRANCH",_PHISICAL_PATH_ADMIN_CONTROLLER.'branch_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_CONFIG",_PHISICAL_PATH_ADMIN_CONTROLLER.'config_controller.php');

	define("_PHISICAL_PATH_ADMIN_CONTROLLER_BANNER",_PHISICAL_PATH_ADMIN_CONTROLLER.'banner_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_BANNER_GROUP",_PHISICAL_PATH_ADMIN_CONTROLLER.'banner_group_controller.php');
	
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_LIBRARY",_PHISICAL_PATH_ADMIN_CONTROLLER.'library_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_TEMPLATE",_PHISICAL_PATH_ADMIN_CONTROLLER.'template_controller.php');

	define("_PHISICAL_PATH_ADMIN_CONTROLLER_PRODUCT",_PHISICAL_PATH_ADMIN_CONTROLLER.'product_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_PRODUCT_PRICE",_PHISICAL_PATH_ADMIN_CONTROLLER.'product_price_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_COLOR",_PHISICAL_PATH_ADMIN_CONTROLLER.'color_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_SIZE",_PHISICAL_PATH_ADMIN_CONTROLLER.'size_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_BRAND",_PHISICAL_PATH_ADMIN_CONTROLLER.'brand_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_UNIT",_PHISICAL_PATH_ADMIN_CONTROLLER.'unit_controller.php');

	define("_PHISICAL_PATH_ADMIN_CONTROLLER_ORDER",_PHISICAL_PATH_ADMIN_CONTROLLER.'order_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_ORDER_DETAIL",_PHISICAL_PATH_ADMIN_CONTROLLER.'order_detail_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_ORDER_BUYER",_PHISICAL_PATH_ADMIN_CONTROLLER.'order_buyer_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_ORDER_RECEIVER",_PHISICAL_PATH_ADMIN_CONTROLLER.'order_receiver_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_ORDER_NOTE",_PHISICAL_PATH_ADMIN_CONTROLLER.'order_note_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_DELIVERYMETHOD",_PHISICAL_PATH_ADMIN_CONTROLLER.'deliverymethod_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_PAYMENTMETHOD",_PHISICAL_PATH_ADMIN_CONTROLLER.'paymentmethod_controller.php');

	define("_PHISICAL_PATH_ADMIN_CONTROLLER_CONTACT_FORM",_PHISICAL_PATH_ADMIN_CONTROLLER.'contactform_controller.php');
	define("_PHISICAL_PATH_ADMIN_CONTROLLER_WIDGET",_PHISICAL_PATH_ADMIN_CONTROLLER.'widget_controller.php');

	/* path file ajax */
	define("_PHISICAL_PATH_ADMIN_AJAX",_PHISICAL_PATH_ADMIN.'ajax_admin.php');

	/* path file classes */
	define("_PHISICAL_PATH_ADMIN_CLASSES",_PHISICAL_PATH_ADMIN.'classes/');
	define("_PHISICAL_PATH_ADMIN_CLASSES_METHOD",_PHISICAL_PATH_ADMIN_CLASSES.'method_admin.php');

	/* path file custom */
	define("_PHISICAL_PATH_ADMIN_VIEW",_PHISICAL_PATH_ADMIN.'view/');
	define("_PHISICAL_PATH_ADMIN_VIEW_LAYOUT",_PHISICAL_PATH_ADMIN.'layout/');
	define("_PHISICAL_PATH_ADMIN_VIEW_DATA",_PHISICAL_PATH_ADMIN.'data/');
	define("_PHISICAL_PATH_ADMIN_VIEW_SCRIPT",_PHISICAL_PATH_ADMIN.'script/');

	/* url file ajax */
	define("_ROOT_PATH_ADMIN_AJAX",_ROOT_PATH_ADMIN.'ajax_admin.php');
?>