<?php 
	/* datatable : max record */
	define('_MAX_RECORD_DATATABLE',10);
	/* status */
	define('_STATUS_DEFAULT_DATATABLE',1);


	/* banner */
	define('_MAX_RECORD_BANNER',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_BANNER',_STATUS_DEFAULT_DATATABLE);

	/* company */
	define('_MAX_RECORD_COMPANY',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_COMPANY',_STATUS_DEFAULT_DATATABLE);

	/* branch - company */
	define('_MAX_RECORD_BRANCH',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_BRANCH',_STATUS_DEFAULT_DATATABLE);

	/* product */
	define('_MAX_RECORD_PRODUCT',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_PRODUCT',_STATUS_DEFAULT_DATATABLE);

	/* price - product */
	define('_MAX_RECORD_PRODUCT_PRICE',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_PRODUCT_PRICE',_STATUS_DEFAULT_DATATABLE);

	/* brand - product */
	define('_MAX_RECORD_BRAND',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_BRAND',_STATUS_DEFAULT_DATATABLE);

	/* unit - product */
	define('_MAX_RECORD_UNIT',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_UNIT',_STATUS_DEFAULT_DATATABLE);

	/* color */
	define('_MAX_RECORD_COLOR',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_COLOR',_STATUS_DEFAULT_DATATABLE);

	/* size */
	define('_MAX_RECORD_SIZE',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_SIZE',_STATUS_DEFAULT_DATATABLE);

	/* content */
	define('_MAX_RECORD_ARTICLE',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_CONTENT',_STATUS_DEFAULT_DATATABLE);

	/* order */
	define('_MAX_RECORD_ORDER',_MAX_RECORD_DATATABLE);

	/* delivery method */
	define('_MAX_RECORD_DELIVERYMETHOD',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_DELIVERYMETHOD',_STATUS_DEFAULT_DATATABLE);

	/* payment method */
	define('_MAX_RECORD_PAYMENTMETHOD',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_PAYMENTMETHOD',_STATUS_DEFAULT_DATATABLE);

	/* template */
	define('_MAX_RECORD_TEMPLATE',_MAX_RECORD_DATATABLE);

	/* form contact */
	define('_MAX_RECORD_FORM_CONTACT',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_FORM_CONTACT',_STATUS_DEFAULT_DATATABLE);

	/* widget */
	define('_MAX_RECORD_WIDGET',_MAX_RECORD_DATATABLE);
	define('_STATUS_DEFAULT_WIDGET',_STATUS_DEFAULT_DATATABLE);




?>